=== Soskar1/Magma-Heart/Assets/Data/DungeonGenerator.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="DungeonGenerator">
		<xs:complexType>
			<xs:all>
				<xs:element name="RoomSpace">
					<xs:complexType>
						<xs:attribute name="XSize" type="xs:int" use="required"/>
						<xs:attribute name="YSize" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="RoomGenerators" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="Boxed">
								<xs:complexType>
									<xs:attribute name="XSize" type="xs:int" use="required"/>
									<xs:attribute name="YSize" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="RandomWalk">
								<xs:complexType>
									<xs:attribute name="Iterations" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="DiffusionLimitedAggregation">
								<xs:complexType>
									<xs:attribute name="TilesToPlace" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="WallGenerator">
								<xs:complexType>
									<xs:attribute name="MaxWallLength" type="xs:int" use="required"/>
									<xs:attribute name="AmountOfWalls" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="TileFill"/>
							<xs:element name="TilePropagation">
								<xs:complexType>
									<xs:attribute name="Length" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="UnreachableTileCapture"/>
							<xs:element name="UnreachableTileDestructor"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Soskar1/Magma-Heart/Assets/Resources/Caves.LocationGenerator.xml
<?xml version ="1.0"?>
<DungeonGenerator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Data/DungeonGenerator.xsd">
	<RoomSpace XSize="30" YSize="30"/>
	
	<RoomGenerators>
		<Boxed XSize="8" YSize="8"/>
		<DiffusionLimitedAggregation TilesToPlace="60"/>
		<TilePropagation Length="2"/>
		<UnreachableTileCapture/>
		<TileFill/>
		<UnreachableTileDestructor/>
	</RoomGenerators>
</DungeonGenerator>
