=== Soskar1/Magma-Heart/Assets/Data/LocationGenerator.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="LocationGenerator">
		<xs:complexType>
			<xs:all>
				<xs:element name="LocationSpace">
					<xs:complexType>
						<xs:attribute name="XSize" type="xs:int" use="required"/>
						<xs:attribute name="YSize" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="RoomSpace">
					<xs:complexType>
						<xs:attribute name="YBorderOffset" type="xs:int" use="required"/>
						<xs:attribute name="XBorderOffset" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="SpacePartitioning">
					<xs:complexType>
						<xs:attribute name="MaxPartitions" type="xs:int" use="required"/>
						<xs:attribute name="RoomXMinSize" type="xs:int" use="required"/>
						<xs:attribute name="RoomYMinSize" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="RoomGenerators" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="Boxed">
								<xs:complexType>
									<xs:attribute name="XSize" type="xs:int" use="required"/>
									<xs:attribute name="YSize" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="RandomWalk">
								<xs:complexType>
									<xs:attribute name="Iterations" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="DiffusionLimitedAggregation">
								<xs:complexType>
									<xs:attribute name="TilesToPlace" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="RoomModifiers" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="TileFill"/>
							<xs:element name="TilePropagation">
								<xs:complexType>
									<xs:attribute name="Length" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="UnreachableTileCapture"/>
							<xs:element name="UnreachableTileDestructor"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="CorridorGenerator">
					<xs:complexType>
						<xs:attribute name="CorridorSize" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Soskar1/Magma-Heart/Assets/Data/Test.LocationGenerator.xml
<?xml version ="1.0"?>
<LocationGenerator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LocationGenerator.xsd">
	<LocationSpace XSize="200" YSize="200"/>
	<RoomSpace XBorderOffset="3" YBorderOffset="3"/>
	<SpacePartitioning MaxPartitions="50" RoomXMinSize="40" RoomYMinSize="40"/>
	
	<RoomGenerators>
		<Boxed XSize="25" YSize="25"/>
		<DiffusionLimitedAggregation TilesToPlace="100"/>
		<TilePropagation Length="2"/>
		<UnreachableTileCapture/>
		<TileFill/>
		<UnreachableTileDestructor/>
	</RoomGenerators>

	<CorridorGenerator CorridorSize="3"/>
</LocationGenerator>
